[tool.isort]
profile = "black"
known_third_party = ["requests", "numpy"]
known_first_party = ["LeetCode"]
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_sort_within_sections = true
combine_as_imports = true
skip_glob = "*.pyi"

[tool.black]
line_length = 79
target_version = ['py312']
skip_string_normalization = true
isolation = true

[tool.pytest]
# Best practices for pytest configuration
addopts = "--maxfail=1 --disable-warnings --cov=. --cov-report=html"
testpaths = ["tests"]  # Set the test folder(s)
